spring:
  application:
    name: rabbitmq-simple
  rabbitmq:
    host: dmxiaoshen.rabbitmq.com
    port: 6672
    username: dmxiaoshen
    password: dmxiaoshen


spring-ext:
  rabbitmq:
    second:
      host: daddress.mq.com
      port: 5672
      username: fydtest
      password: fydtest