spring:
  mail:
    host: smtp.qq.com
    username: hsg@dmxiaoshen.com
    password: kkk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true